### ISSUE TITLE
Invalid shorthand property initializer

### ISSUE THREAD

**Issue by liberaliscomputing** [hms-dbmi/pic-sure-hpds-ui#25]
Found this line (https://github.com/hms-dbmi/pic-sure-hpds-ui/blob/master/pic-sure-hpds-ui/src/test/javascript/queryBuilderSpec.js#L30) causes MVN package building to fail due to JavaScript syntax error. Below works:

```javascript
expect(queryBuilder.createQuery([new filter.Model({inclusive:true, searchTerm: "Asthma", and: false, theList: null, constrainByValue: true, valueType: "STR"})])).toEqual(expectedQuery);
```

**Comment by namdets** [comment]
Fixed in https://github.com/hms-dbmi/pic-sure-hpds-ui/commit/c10bfb39b9c362b395eb161df34d12e8fce5e167

Thanks!
